# Generated by Django 3.2.7 on 2021-09-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='origin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
