# Generated by Django 3.2.7 on 2021-09-19 19:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_term_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
