# Generated by Django 3.2.7 on 2021-09-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_term_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='origin',
            new_name='body',
        ),
    ]
