# Generated by Django 3.2.7 on 2021-09-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_origin_term_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='description',
        ),
        migrations.AddField(
            model_name='term',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='body',
            field=models.TextField(),
        ),
    ]
