# Generated by Django 3.2.7 on 2021-09-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210919_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
