# Generated by Django 3.2.7 on 2021-09-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_term_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
